### PR TITLE
Add qt-faststart

### PR DESCRIPTION
**Pull request by roideuniverse**
Add qt-faststart binary

The indentation was way off so I changed it, Makes it a bit difficult to review.

### CODE REVIEW

**Comment by BrandonRomano** [comment]
:+1:

**Comment by tmilewski** [comment]
Should we try and push this upstream?

**Comment by BrandonRomano** [comment]
Probably not -- we've customized this like wayy too much for them to willingly accept this PR

**Comment by tmilewski** [comment]
No problem, figured I'd ask.

On Wed, Sep 23, 2015 at 3:07 PM, Brandon Romano notifications@github.com
wrote:

> Probably not -- we've customized this like wayy too much for them to
> willingly accept this PR
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/carrot/android-ffmpeg-java/pull/5#issuecomment-142699917
> .

## 

Tom Milewski
Director of Engineering | Carrot Creative a VICE company
718.395.7934 | carrot.is/tom | @tmilewski http://twitter.com/tmilewski

**Comment by roideuniverse** [comment]
Probably not the code, but we can try to push the binary ?

**Comment by BrandonRomano** [comment]
Yeah I think we could try that definitely

**Pull request merged**
